name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup env
      run: "export CC=$(which gcc) && export CXX=$(which g++)"
    - name: install deps
      uses: ConorMacBride/install-package@v1.1.0
      with: 
        brew: wxwidgets 
    # - name: configure
    #   run: ./configure
    - name: make
      run: make release
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
    - name: upload build
      uses: actions/upload-artifact@v3.2.1
      with:
        name: mapfab
        path: mapfab
